### ISSUE TITLE
I want to invest but I have no money :(

### ISSUE THREAD

**Issue by bhavsarpratik** [amitness/auto-nepse#1]

**Comment by amitness** [comment]
![](https://c.tenor.com/gaEpIfzxzPEAAAAM/pedro-monkey-puppet.gif)
![Screenshot_20210817-202338_Lightning](https://user-images.githubusercontent.com/8587189/129746579-b90208da-6736-4146-8fb0-ff868d34c322.jpg)

**Comment by bhavsarpratik** [comment]
The majority think I earn 0-50 which mean it can be anything in that range!

**Comment by amitness** [comment]
My guess is the majority is wrong here. People can literally figure out the salary range for your previous company through angel.co. You must be earning higher than that in your new role.

**Comment by amitness** [comment]
Anyway closing this 😂
